Repository Alfresco/share, pull requests merged in 2020-04, with the labels that each got.

#186 Full fix for MNT-21162 in rest of affected languages and also full fi…
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/document-details/document-versions.get_de.properties
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/document-details/document-versions.get_es.properties
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/document-details/document-versions.get_fr.properties
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/document-details/document-versions.get_nb.properties
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/document-details/document-versions.get_nl.properties
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/document-details/document-versions.get_pt_BR.properties
Labels: PR: reviewed-approved

#187 GOOGLEDOCS-473: updated pom.xml file to use 'GoogleDocs 3.2.0-RC1' instead of 'GoogleDocs 3.2.0-A4'"
  packaging/docker/pom.xml
Labels: PR: reviewed-approved

#189 GOOGLEDOCS-497: Updated pom.xml file to use 'GoogleDocs 3.2.0-RC3'
  packaging/docker/pom.xml
Labels: PR: partially-approved

#190 GOOGLEDOCS-497: Updated pom.xml file to use 'GoogleDocs 3.2.0-RC3' (cherry-picked from master)
  packaging/docker/pom.xml
Labels: PR: unreviewed

#182 MNT-20347 : add the executable jar for encrypt strings.
  share-encryption/README.md
  share-encryption/pom.xml
  share-encryption/src/main/java/org/alfresco/encryptor/PublicPrivateKeyShareStringEncryptor.java
  share-encryption/src/main/java/org/alfresco/encryptor/ShareStringEncryption.java
  share/pom.xml
  share/src/main/java/org/alfresco/web/site/servlet/config/AlfrescoEncryptionElementConvert.java
  share/src/main/java/org/alfresco/web/site/servlet/config/KerberosConfigElementReader.java
  share/src/test/java/org/alfresco/web/config/converter/EncryptionElementConverterTest.java
  share/src/test/resources/alfresco/web-extension/alfrescoSpringKey.pri
  share/src/test/resources/alfresco/web-extension/alfrescoSpringKey.pub
Labels: PR: unreviewed

#192 MNT-21438
  share/src/main/java/org/alfresco/web/site/servlet/MTAuthenticationFilter.java
Labels: PR: reviewed-approved
