Repository Alfresco/share, pull requests merged in 2020-10, with the labels that each got.

#296 MNT-21719 Add check for auth user attribute in http session
  share/src/main/java/org/alfresco/web/site/EditionInterceptor.java
Labels: PR: partially-approved

#297 LOC-259 Terminology Fixes to the FRENCH bundle
  share-services/src/main/resources/alfresco/messages/data-list-model_fr.properties
  share-services/src/main/resources/alfresco/templates/webscripts/org/alfresco/slingshot/application/logo.post_fr.properties
  share-services/src/main/resources/alfresco/templates/webscripts/org/alfresco/slingshot/profile/uploadavatar.post_fr.properties
  share/src/main/resources/alfresco/messages/slingshot_fr.properties
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/documentlibrary/documentlist-v2.get_fr.properties
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/documentlibrary/documentlist.get_fr.properties
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/documentlibrary/myfiles.get_fr.properties
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/documentlibrary/repo.get_fr.properties
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/documentlibrary/sharedfiles.get_fr.properties
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/invite/addemail.get_fr.properties
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/profile/user-notifications.get_fr.properties
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/profile/user-sites.get_fr.properties
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/quickshare/header.get_fr.properties
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/rules/config/rule-config-action.get_fr.properties
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/upload/dnd-upload.get_fr.properties
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/upload/flash-upload.get_fr.properties
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/upload/html-upload.get_fr.properties
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/modules/email-form.get_fr.properties
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/modules/rules/actions/workflow.get_fr.properties
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/modules/rules/rules-property-picker.get_fr.properties
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/share/pages/admin-console/custom-model-manager.get_fr.properties
  wcmquickstart-module/wcmquickstartmodule/src/main/amp/config/alfresco/module/org_alfresco_module_wcmquickstart/model/website-model_fr.properties
  wcmquickstart-module/wcmquickstartwebsite/src/main/resources/alfresco/messages/common_fr.properties
  web-framework-commons/src/main/resources/alfresco/messages/common_fr.properties
Labels: PR: partially-approved

#298 LOC-259- fixes to UI terminology in DUTCH bundle
  share/src/main/resources/alfresco/messages/slingshot_nl.properties
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/admin/replication-job.get_nl.properties
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/console/repository/replication-jobs.get_nl.properties
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/console/usersgroups/groups.get_nl.properties
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/site/customise-pages.get_nl.properties
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/modules/blog/config/config-blog.get_nl.properties
Labels: PR: partially-approved

#304 APPS-553: Share version 7.0.0-M2 doesn't display the correct version
  .travis.yml
Labels: PR: partially-approved

#303 APPS-422: SHARE - Pipeline improvement with K8s and AWS
  .travis.yml
  _ci/build.sh
  _ci/delete-env.sh
  _ci/deploy_k8s.sh
  _ci/execute_share_web.sh
  _ci/route53.json
  _ci/start-compose.sh
  _ci/stop-compose.sh
  _ci/values-for-ingress-travis-env.yaml
  _ci/wait-for-share-start.sh
Labels: PR: unreviewed

#313 Upgrade ACS helm chart after repo image upgrade
  _ci/deploy_k8s.sh
Labels: PR: partially-approved

#316 Feature/apps 559 v2
  .travis.yml
  _ci/deploy_k8s.sh
  _ci/init_tag.sh
Labels: PR: partially-approved

#317 APPS-563: [SHARE] Investigate impact of removing myFaces libs
  share-services/pom.xml
  share/pom.xml
  wcmquickstart-module/wcmquickstartwebsite/pom.xml
  web-editor-plugin/pom.xml
  web-editor-samples/customer-site/pom.xml
  web-editor/pom.xml
  web-framework-commons/pom.xml
Labels: PR: partially-approved

#319 MNT-21922 : Delay spotted when render preview
  pom.xml
Labels: PR: reviewed-approved

#318 MNT-21922 : Delay spotted when render preview
  pom.xml
Labels: PR: reviewed-approved

#324 Update repo replication count to 1
  _ci/deploy_k8s.sh
Labels: PR: partially-approved

#325 MNT-21877: [Security] commons-collections vulnerability
  share-services/pom.xml
  share/pom.xml
  share/src/main/java/org/alfresco/web/scripts/ShareManifest.java
  share/src/main/java/org/alfresco/web/site/servlet/config/AIMSConfig.java
  wcmquickstart-module/wcmquickstartwebsite/pom.xml
  web-editor-plugin/pom.xml
  web-editor-samples/customer-site/pom.xml
  web-editor/pom.xml
  web-framework-commons/pom.xml
Labels: PR: partially-approved

#323 fix/APPS-592
  .travis.yml
  _ci/execute_share_web.sh
Labels: PR: partially-approved
