Repository Alfresco/share, pull requests merged in 2020-08, with the labels that each got.

#258 APPS-314: update dependencies in concordance with acs-packaging
  pom.xml
  share-encryption/pom.xml
  share-services/pom.xml
  share/pom.xml
  wcmquickstart-module/wcmquickstartclientapi/pom.xml
  wcmquickstart-module/wcmquickstartmodule/pom.xml
  wcmquickstart-module/wcmquickstartwebsite/pom.xml
  web-editor-plugin/pom.xml
  web-editor-samples/customer-site/pom.xml
  web-editor/pom.xml
  web-framework-commons/pom.xml
Labels: PR: reviewed-approved

#259 Modify the scripts to release from master a new version 7.0.0
  .travis.yml
  _ci/build.sh
  _ci/init_tag.sh
  _ci/maven_release.sh
Labels: PR: unreviewed

#260 Update .travis.yml
  .travis.yml
  _ci/init_tag.sh
Labels: PR: partially-approved

#261 Add travis log and changes for release.
  .travis.yml
  _ci/build.sh
  _ci/execute_share_web.sh
  _ci/init_tag.sh
  _ci/start-compose.sh
Labels: PR: reviewed-approved

#262 apply 777 permision on *.sh file
  _ci/maven_release.sh
Labels: PR: reviewed-approved

#263 APPS-314: add correct version, add release parameter.
  _ci/maven_release.sh
  packaging/docker/docker-compose/.env
  pom.xml
Labels: PR: partially-approved

#264 APPS-314: Added release notes.
  docs/Release.md
Labels: PR: unreviewed

#265 ATS-808: Bump AIS to 1.2.1-RC2
  packaging/docker-aws/pom.xml
Labels: PR: partially-approved

#257 Update dependencies suggested by dependabot in a fork of Share
  packaging/docker-aws/pom.xml
  packaging/docker/pom.xml
  pom.xml
  share-services/pom.xml
  share/pom.xml
  wcmquickstart-module/pom.xml
  wcmquickstart-module/wcmquickstartclientapi/pom.xml
  wcmquickstart-module/wcmquickstartwebsite/pom.xml
  web-editor-plugin/pom.xml
  web-editor-samples/customer-site/pom.xml
  web-editor/pom.xml
  web-framework-commons/pom.xml
Labels: PR: partially-approved

#267 APPS-0000: Add dependabot configuration file
  .github/dependabot.yml
Labels: PR: partially-approved

#266 APPS-0000: Release share 7.0.0-A2 [release]
  .travis.yml
  pom.xml
Labels: PR: unreviewed

#273 ATS-821 Update AIS to 1.2.1
  packaging/docker-aws/pom.xml
Labels: PR: partially-approved

#274 FIX for MNT-21814 - improvement to UI translations in Brazilian Portu…
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/share/pages/faceted-search/faceted-search-config.get_pt_BR.properties
Labels: PR: partially-approved

#278 APPS-443: Add tests from user group to run in pipeline
  .travis.yml
Labels: PR: partially-approved
