Repository Alfresco/share, pull requests merged in 2020-06, with the labels that each got.

#216 Revert "SFDCENG-804: Check SFDC integration compatibility with SameSi…
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/guest/login.get.html.ftl
  share/src/main/webapp/components/guest/login.js
Labels: PR: partially-approved

#218 [MNT-20091] Added check to filter cm:taggable aspect with null
  share-services/src/main/resources/alfresco/templates/webscripts/org/alfresco/collaboration/tagQuery.get.js
Labels: PR: unreviewed

#217 [MNT-20091] Added check to filter cm:taggable aspect with null
  share-services/src/main/resources/alfresco/templates/webscripts/org/alfresco/collaboration/tagQuery.get.js
Labels: PR: unreviewed

#221 LOC-227 Fix for ITALIAN bundle. Change of term "Library" (in EN). "Ra…
  share/src/main/resources/alfresco/messages/slingshot_it.properties
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/console/tag-management.get_it.properties
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/dashboard/customise-dashlets.get_it.properties
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/dashlets/docsummary.get_it.properties
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/dashlets/dynamic-welcome.get_it.properties
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/dashlets/imagesummary.get_it.properties
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/documentlibrary/documentlist-v2.get_it.properties
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/documentlibrary/documentlist.get_it.properties
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/documentlibrary/myfiles.get_it.properties
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/documentlibrary/repo.get_it.properties
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/documentlibrary/sharedfiles.get_it.properties
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/documentlibrary/toolbar.get_it.properties
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/documentlibrary/tree.get_it.properties
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/modules/documentlibrary/global-folder.get_it.properties
  web-framework-commons/src/main/resources/alfresco/messages/common_it.properties
Labels: PR: partially-approved

#228 SHA-2369 : AIMS remove admin tools bits
  share/src/main/java/org/alfresco/web/scripts/AimsStatusWebScript.java
  share/src/main/resources/alfresco/messages/slingshot.properties
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/console/usersgroups/users.get.html.ftl
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/console/usersgroups/users.get.js
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/profile/change-password.get.html.ftl
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/profile/change-password.get.js
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/profile/userprofile.get.html.ftl
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/profile/userprofile.get.js
  share/src/main/resources/alfresco/slingshot-application-context.xml
Labels: PR: partially-approved

#231 APPS-193: Fixed the issue
  share/src/main/java/org/alfresco/web/site/servlet/AIMSFilter.java
  share/src/main/java/org/alfresco/web/site/servlet/config/AIMSConfig.java
  share/src/main/java/org/alfresco/web/site/servlet/config/AIMSConfigElement.java
  share/src/main/java/org/alfresco/web/site/servlet/config/AIMSConfigElementReader.java
  share/src/main/resources/alfresco/share-config.xml
  share/src/main/resources/alfresco/slingshot-application-context.xml
  share/src/main/resources/share-config.properties
  share/src/test/java/org/alfresco/web/config/properties/AIMSConfigTest.java
  share/src/test/resources/alfresco/module/shareProperties/share-config.properties
  share/src/test/resources/test-config-aims-basic.xml
Labels: PR: unreviewed

#232 APPS-153: Fixed the issue.
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/head/resources.get.html.ftl
  web-framework-commons/src/main/webapp/js/alfresco.js
Labels: PR: partially-approved

#207 MNT-19466 - fix AOS: "Edit Online" does not work for RTF files
  share/src/main/resources/alfresco/slingshot-documentlibrary-context.xml
  share/src/main/webapp/components/documentlibrary/actions.js
Labels: PR: reviewed-approved

#204 MNT-19466 - fix AOS: "Edit Online" does not work for RTF files
  share/src/main/resources/alfresco/slingshot-documentlibrary-context.xml
  share/src/main/webapp/components/documentlibrary/actions.js
Labels: PR: reviewed-approved

#202 MNT-18448 - fix AOS: "Edit Online" does not work for MS-Visio files
  share/src/main/resources/alfresco/slingshot-documentlibrary-context.xml
  share/src/main/webapp/components/documentlibrary/actions.js
Labels: PR: unreviewed

#206 MNT-18448 - fix AOS: "Edit Online" does not work for MS-Visio files
  share/src/main/resources/alfresco/slingshot-documentlibrary-context.xml
  share/src/main/webapp/components/documentlibrary/actions.js
Labels: PR: unreviewed

#224 [MNT-19466] Make RTF documents available for edit online
  share/src/main/resources/alfresco/slingshot-documentlibrary-context.xml
  share/src/main/webapp/components/documentlibrary/actions.js
Labels: PR: unreviewed

#225 [MNT-19466] Make RTF documents available for edit online
  share/src/main/resources/alfresco/slingshot-documentlibrary-context.xml
  share/src/main/webapp/components/documentlibrary/actions.js
Labels: PR: unreviewed

#226 [MNT-18448] Make Microsoft Visio documents available for edit online
  share/src/main/resources/alfresco/slingshot-documentlibrary-context.xml
  share/src/main/webapp/components/documentlibrary/actions.js
Labels: PR: unreviewed

#227 [MNT-18448] Make Microsoft Visio documents available for edit online
  share/src/main/resources/alfresco/slingshot-documentlibrary-context.xml
  share/src/main/webapp/components/documentlibrary/actions.js
Labels: PR: unreviewed

#237 [MNT-18448] Added missing visio extensions protocol
  share/src/main/webapp/components/documentlibrary/actions.js
Labels: PR: unreviewed

#238 [MNT-18448] Added missing visio extensions protocol
  share/src/main/webapp/components/documentlibrary/actions.js
Labels: PR: unreviewed

#235 ATS-786 - bump AIS to 1.2.0-RC1
  packaging/docker-aws/pom.xml
Labels: PR: partially-approved

#239 MNT-18448 MNT-19466: Reverting RTF and Visio extensions
  share/src/main/resources/alfresco/slingshot-documentlibrary-context.xml
  share/src/main/webapp/components/documentlibrary/actions.js
Labels: PR: reviewed-approved

#240 MNT-18448 MNT-19466: Reverting RTF and Visio extensions
  share/src/main/resources/alfresco/slingshot-documentlibrary-context.xml
  share/src/main/webapp/components/documentlibrary/actions.js
Labels: PR: partially-approved

#236 APPS-153: Fix the back button issue.
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/head/resources.get.html.ftl
  web-framework-commons/src/main/webapp/js/alfresco.js
Labels: PR: partially-approved

#243 LOC-234 - Updated strings in 10 languages based on Master branch for …
  share-services/src/main/resources/alfresco/messages/data-list-model_nl.properties
  share/src/main/resources/alfresco/messages/slingshot_de.properties
  share/src/main/resources/alfresco/messages/slingshot_es.properties
  share/src/main/resources/alfresco/messages/slingshot_fr.properties
  share/src/main/resources/alfresco/messages/slingshot_it.properties
  share/src/main/resources/alfresco/messages/slingshot_ja.properties
  share/src/main/resources/alfresco/messages/slingshot_nb.properties
  share/src/main/resources/alfresco/messages/slingshot_nl.properties
  share/src/main/resources/alfresco/messages/slingshot_pt_BR.properties
  share/src/main/resources/alfresco/messages/slingshot_ru.properties
  share/src/main/resources/alfresco/messages/slingshot_zh_CN.properties
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/calendar/view.get_nl.properties
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/console/application.get_de.properties
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/dashboard/customise-dashlets.get_nl.properties
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/dashlets/activity-list.get_nl.properties
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/dashlets/colleagues.get_nl.properties
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/dashlets/imagesummary.get_nl.properties
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/workflow/filter/assignee.get_nl.properties
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/workflow/task-edit-header.get_nl.properties
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/modules/documentlibrary/workflow.get_nl.properties
Labels: PR: partially-approved

#242 APPS-212: Make sure that sslRequired won't be set with an invalid value
  share/src/main/java/org/alfresco/web/site/servlet/config/AIMSConfig.java
  share/src/main/resources/share-config.properties
  share/src/test/java/org/alfresco/web/config/properties/AIMSConfigTest.java
  share/src/test/resources/alfresco/module/shareProperties/share-config.properties
Labels: PR: partially-approved

#241 added new version of bouncycastel
  pom.xml
Labels: PR: reviewed-approved

#244 ATS-774: Bump to final AIS 1.2.0
  packaging/docker-aws/pom.xml
Labels: PR: partially-approved
