Repository Alfresco/share, pull requests merged in 2020-05, with the labels that each got.

#195 GOOGLEDOCS-490: Updated pom.xml file to use 'Google Docs-3.2.0' instead of 'Google Docs 3.2.0-RC3'
  packaging/docker/pom.xml
Labels: PR: partially-approved

#196 ACS-120 - Removed commons-lang that is being brought in transitively in alfresco-remote-api
  share-services/pom.xml
Labels: PR: unreviewed

#197 ACS-120 - Added scope "provided" to commons-lang library to avoid gen…
  share-services/pom.xml
Labels: PR: unreviewed

#199 APPS-118: update spring to 5.1.15
  pom.xml
  share-services/pom.xml
  wcmquickstart-module/wcmquickstartmodule/pom.xml
  wcmquickstart-module/webquickstart-tests/pom.xml
  web-framework-commons/pom.xml
Labels: PR: reviewed-approved

#200 APPS-85: comment the AIMS Filter for better tests.
  share/src/main/webapp/WEB-INF/web.xml
Labels: PR: reviewed-approved

#201 MNT-20195: Avoid displaying sensitive information
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/html.status.ftl
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/errorcode.lib.ftl
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/modules/html.status.ftl
Labels: PR: partially-approved

#208 [MNT-20091] Added check to filter cm:taggable aspect with null
  share-services/src/main/resources/alfresco/templates/webscripts/org/alfresco/collaboration/tagQuery.get.js
Labels: PR: reviewed-approved

#209 [MNT-20091] Added check to filter cm:taggable aspect with null
  share-services/src/main/resources/alfresco/templates/webscripts/org/alfresco/collaboration/tagQuery.get.js
Labels: PR: unreviewed

#210 [MNT-20091] Added check to filter cm:taggable aspect with null
  share-services/src/main/resources/alfresco/templates/webscripts/org/alfresco/collaboration/tagQuery.get.js
Labels: PR: unreviewed

#213 SFDCENG-804: Check SFDC integration compatibility with SameSite=Lax c…
  share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/guest/login.get.html.ftl
  share/src/main/webapp/components/guest/login.js
Labels: PR: partially-approved

#214 SHA-2457: added. share-config.propeties support for share.
  pom.xml
  share/src/main/java/org/alfresco/web/site/servlet/AIMSFilter.java
  share/src/main/java/org/alfresco/web/site/servlet/SSOAuthenticationFilter.java
  share/src/main/java/org/alfresco/web/site/servlet/SlingshotLogoutController.java
  share/src/main/java/org/alfresco/web/site/servlet/config/AIMSConfig.java
  share/src/main/java/org/alfresco/web/site/servlet/config/AIMSConfigElement.java
  share/src/main/java/org/alfresco/web/site/servlet/config/AIMSConfigElementReader.java
  share/src/main/resources/alfresco/share-config.xml
  share/src/main/resources/alfresco/slingshot-application-context.xml
  share/src/main/resources/share-config.properties
  share/src/main/webapp/WEB-INF/keycloak.json
  share/src/test/java/org/alfresco/web/config/forms/FormConfigBasicTest.java
  share/src/test/java/org/alfresco/web/config/properties/AIMSConfigTest.java
  share/src/test/java/org/alfresco/web/config/util/BaseTest.java
  share/src/test/resources/alfresco/module/shareProperties/share-config.properties
  share/src/test/resources/test-config-aims-basic.xml
  share/src/test/resources/test-config-forms-basic.xml
Labels: PR: reviewed-approved
